#!/usr/bin/env bash
#Bash script to install nginx on your web-01
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i "s/^\troot \/var\/www\/html;/&\n\n\tlocation \/redirect_me {return 301 https:\/\/www.youtube.com\/;}/" /etc/nginx/sites-available/default
sudo service nginx reload
