#!/usr/bin/env bash
#Bash script to install nginx on your web-01
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo sed -i "s/^\troot \/var\/www\/html;/&\n\n\tlocation \/redirect_me {return 301 https:\/\/www.youtube.com\/;}/" /etc/nginx/sites-available/default
sudo sed -i "s/^\troot \/var\/www\/html;/&\n\n\terror_page 404 \/404.html;\n\n\tlocation = \/404.html {internal;}/" /etc/nginx/sites-available/default
sudo service nginx reload
