#!/usr/bin/env bash
# Generates a MySQL dump and creates a compressed archive out of it

mysql_password="$1"
filename="backup.sql"
archive_name="$(date +"%d-%m-%Y").tar.gz"

mysqldump -u root -p"$mysql_password" --all-databases > "$filename"
tar -czvf "$archive_name" "$filename"
