#!/usr/bin/env bash
#Bash script that displays Best School 10 times, but for the 9th HI insted

i="1"
while (( i <= "10" ))
do
	echo "Best School"
	if (( i == 9 ))
	then
		echo "Hi"
	fi
	((i++))
done
