#!/usr/bin/env bash
#Write a Bash script that configures an Ubuntu server with the below requirements.
#
#Requirements:
#
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8.

cp /etc/hosts hosts1
sed -i "s/^127.0.0.1/127.0.0.2/" hosts1
echo "8.8.8.8	facebook.com" >> hosts1
cp hosts1 /etc/hosts

